language: objective-c
osx_image: xcode7

#deploy:
#  provider: script
#  script: ./scripts/push.sh
#  on:
#    tags: true

before_install:
- gem install xcpretty

script:
- xcodebuild -workspace SDCAlertView.xcworkspace -scheme "SDCAlertView"
  -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -s
- xcodebuild -workspace SDCAlertView.xcworkspace -scheme "Example" -destination
  "platform=iOS Simulator,name=iPhone 6s" | xcpretty -s

